
version: 2

sources:
  - name: bq
    database: bigquery-public-data
    schema: stackoverflow
    tables:
      - name: posts_questions
      - name: comments
      - name: stackoverflow_posts
      - name: posts_answers
      - name: users
      - name: badges

models:
    - name: questions_answers_combined
      description: "Model for joining stackoverflow questions and answers table, and removing unessential columns from answers table."
      columns:
          - name: answer_id
            description: "Each answer's id as well as the primary key for this table"
            tests:
                - unique
                - not_null
    - name: users_questions
      description: "Join users questions_answers_join table to get a full table of all questions asked by each user (posts made)"
      columns:
          - name: id
            description: "Each user's id as well as the primary key for this table"
            tests:
                - unique
                - not_null
          - name: question_id
            description: "Each question's id"
            tests:
                - unique
                - not_null
    - name: users_answers
      description: "Join users questions_answers_join table to get a full table of all answers given by each user"
      columns:
          - name: id
            description: "Each user's id as well as the primary key for this table"
            tests:
                - unique
                - not_null
          - name: answer_id
            description: "Each answer's id"
            tests:
                - unique
                - not_null
    - name: users_badges
      description: "Pivot the badges table"
      columns:
          - name: user_id
            description: "Each user's id as well as the primary key for this table"
            tests:
                - unique
                - not_null
    - name: top_badges
      description: "Select top 10 most commonly won badges"
      columns:
          - name: name
            tests:
                - not_null